--------------------------------------------------------
--  Fichier créé - dimanche-octobre-31-2021   
--------------------------------------------------------
DROP TABLE "SYSTEM"."VOITURE";
DROP TABLE "SYSTEM"."FOURNISSEUR";
DROP TABLE "SYSTEM"."EMPLOYÉE";
DROP TABLE "SYSTEM"."CIIENT";
--------------------------------------------------------
--  DDL for Table VOITURE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."VOITURE" 
   (	"MATRICULE" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(15 BYTE), 
	"PRIX" VARCHAR2(10 BYTE), 
	"DATE_SORTIS" VARCHAR2(25 BYTE), 
	"ID_FOURNISSEUR" VARCHAR2(30 BYTE), 
	"CIN_CLIENT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNISSEUR
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."FOURNISSEUR" 
   (	"ID" VARCHAR2(30 BYTE), 
	"NUM_TÉLÉPHONE" NUMBER, 
	"EMAIL" VARCHAR2(50 BYTE), 
	"ADRESSE" VARCHAR2(60 BYTE), 
	"TYPE_VOITURE" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYÉE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EMPLOYÉE" 
   (	"ID_EMPLOYÉ" VARCHAR2(30 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"NOMBRE_HEURES" NUMBER, 
	"ADRESSE_MAIL" VARCHAR2(20 BYTE), 
	"NUM8TELEPHONE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CIIENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CIIENT" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ADRESSE_CLIENT" VARCHAR2(50 BYTE), 
	"NUM_CLIENT" NUMBER, 
	"ADRESSE_MAIL" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.VOITURE
SET DEFINE OFF;
REM INSERTING into SYSTEM.FOURNISSEUR
SET DEFINE OFF;
REM INSERTING into SYSTEM."EMPLOYÉE"
SET DEFINE OFF;
REM INSERTING into SYSTEM.CIIENT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index VOITURE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."VOITURE_PK" ON "SYSTEM"."VOITURE" ("MATRICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOURNISSEUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."FOURNISSEUR_PK" ON "SYSTEM"."FOURNISSEUR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYÉE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."EMPLOYÉE_PK" ON "SYSTEM"."EMPLOYÉE" ("ID_EMPLOYÉ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CIIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CIIENT_PK" ON "SYSTEM"."CIIENT" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table VOITURE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."VOITURE" ADD CONSTRAINT "VOITURE_PK" PRIMARY KEY ("MATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."VOITURE" MODIFY ("CIN_CLIENT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."VOITURE" MODIFY ("ID_FOURNISSEUR" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."VOITURE" MODIFY ("DATE_SORTIS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."VOITURE" MODIFY ("PRIX" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."VOITURE" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."VOITURE" MODIFY ("MATRICULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOURNISSEUR
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."FOURNISSEUR" ADD CONSTRAINT "FOURNISSEUR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."FOURNISSEUR" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."FOURNISSEUR" MODIFY ("TYPE_VOITURE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."FOURNISSEUR" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."FOURNISSEUR" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."FOURNISSEUR" MODIFY ("NUM_TÉLÉPHONE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYÉE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLOYÉE" ADD CONSTRAINT "EMPLOYÉE_PK" PRIMARY KEY ("ID_EMPLOYÉ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."EMPLOYÉE" MODIFY ("ID_EMPLOYÉ" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYÉE" MODIFY ("NUM8TELEPHONE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYÉE" MODIFY ("ADRESSE_MAIL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYÉE" MODIFY ("NOMBRE_HEURES" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYÉE" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYÉE" MODIFY ("NOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CIIENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CIIENT" ADD CONSTRAINT "CIIENT_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CIIENT" MODIFY ("CIN" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CIIENT" MODIFY ("ADRESSE_MAIL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CIIENT" MODIFY ("NUM_CLIENT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CIIENT" MODIFY ("ADRESSE_CLIENT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CIIENT" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CIIENT" MODIFY ("NOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table VOITURE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."VOITURE" ADD CONSTRAINT "VOITURE_FK" FOREIGN KEY ("ID_FOURNISSEUR")
	  REFERENCES "SYSTEM"."FOURNISSEUR" ("ID") ENABLE;
  ALTER TABLE "SYSTEM"."VOITURE" ADD CONSTRAINT "VOITURE_FK1" FOREIGN KEY ("CIN_CLIENT")
	  REFERENCES "SYSTEM"."CIIENT" ("CIN") ENABLE;
